"""results/INDEX.md: every results/ path and figure referenced in RESULTS.md, resolved to files on disk, with the
phase section that references it. Brace patterns like results/phase1b_{12k,30k}_checks.json are expanded.
Read-only with respect to results (only INDEX.md is written).

  .venv/bin/python scripts/make_index.py
"""
import glob
import itertools
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_MD = os.path.join(ROOT, "RESULTS.md")


def expand(pat):
    m = re.search(r"\{([^{}]*)\}", pat)
    if not m:
        return [pat]
    out = []
    for opt in m.group(1).split(","):
        out += expand(pat[:m.start()] + opt + pat[m.end():])
    return out


def main():
    lines = open(RESULTS_MD).read().split("\n")
    phase = "preamble"
    refs = {}  # resolved path -> {"phases": [...], "raw": set()}
    pat = re.compile(r"results/[A-Za-z0-9_./{},*-]+")
    for ln in lines:
        if ln.startswith("## "):
            phase = ln[3:].strip()
        for raw in pat.findall(ln.replace("`", " ")):
            raw = raw.rstrip(".,;:")
            # comma-joined command-line lists (results/a.json,results/b.json) and format placeholders ({method}, {N}, ...)
            parts = raw.split(",results/")
            parts = [parts[0]] + ["results/" + x for x in parts[1:]]
            for part in parts:
                part = re.sub(r"\{[A-Za-z_:0-9]+\}", "*", part)
                for p in expand(part):
                    key = p
                    refs.setdefault(key, {"phases": [], "raw": set()})
                    if phase not in refs[key]["phases"]:
                        refs[key]["phases"].append(phase)
                    refs[key]["raw"].add(raw)
            continue
            for p in expand(raw):
                key = p
                refs.setdefault(key, {"phases": [], "raw": set()})
                if phase not in refs[key]["phases"]:
                    refs[key]["phases"].append(phase)
                refs[key]["raw"].add(raw)
    rows = []
    for key in sorted(refs):
        full = os.path.join(ROOT, key)
        if any(ch in key for ch in "*?"):
            matches = glob.glob(full)
            status = f"{len(matches)} matches" if matches else "NO MATCH"
            kind = "pattern"
        elif os.path.isdir(full):
            n = sum(len(f) for _, _, f in os.walk(full))
            status = f"directory, {n} files"
            kind = "dir"
        elif os.path.exists(full):
            status = f"{os.path.getsize(full) / 1024:.0f} KB"
            kind = {".png": "figure", ".md": "table", ".json": "data", ".pdf": "figure"}.get(os.path.splitext(key)[1], "file")
        else:
            status = "MISSING"
            kind = "?"
        rows.append((key, kind, status, refs[key]["phases"]))
    # figures on disk not referenced by name in RESULTS.md (they are referenced via tags), listed for completeness
    figs = sorted(glob.glob(os.path.join(ROOT, "results", "fig_*.png")) + glob.glob(os.path.join(ROOT, "results", "*", "fig_*.png")))
    extra = [os.path.relpath(f, ROOT) for f in figs if os.path.relpath(f, ROOT) not in refs]
    paper = sorted(glob.glob(os.path.join(ROOT, "results", "paper_figs", "*")))
    md = ["# results/INDEX.md: tables and figures referenced in RESULTS.md", "",
          "Generated by `scripts/make_index.py` from RESULTS.md. Each row is a `results/` path referenced in RESULTS.md (brace patterns expanded), "
          "its resolution on disk, and the RESULTS.md section(s) that reference it. Directories excluded from git (sample roots) are marked as directories with their file counts.",
          "", "| referenced path | kind | on disk | referenced in section(s) |", "|---|---|---|---|"]
    for key, kind, status, phases in rows:
        md.append(f"| `{key}` | {kind} | {status} | {'; '.join(phases)} |")
    md += ["", "## Figures on disk referenced only through their analysis tag", ""]
    for f in extra:
        tag = os.path.basename(f)
        md.append(f"- `{f}`: reward vs NFE figure of a tagged analysis run (`analyze_phase2 --tag ...`, or `m3/analyze_m3.py` for the m3 one), {os.path.getsize(f) // 1024} KB")
    md += ["", "## Paper figure set (`results/paper_figs/`, vector PDF + LaTeX tables, `scripts/paper_figs.py`)", ""]
    for f in paper:
        md.append(f"- `{os.path.relpath(f, ROOT)}`")
    md += ["", "## Bulk outputs not tracked in git (see .gitignore)", "",
           "- dance sample roots `samples_*/` (npz motion + logs), twist rollouts `data/twist*/rollouts/`, within-set rollouts `data/twist_rep/sets/`, oracle sets `data/twist_rep/oracle_sets/`, checkpoints `runs/*/*.pt` and twist `.pt` files, `data/cache/`;",
           "- music per-sequence directories (wav, latents, per-sequence log.json): `results/m0/{acestep,sa3_*}/`, `results/m1/{samples,variance,determinism,steps_probe,smoke}/`, `results/m1b/{b1,b2,smoke_*}/`, `results/m2/{b2,smoke}/`, `results/m3/samples/`."]
    open(os.path.join(ROOT, "results", "INDEX.md"), "w").write("\n".join(md) + "\n")
    print(f"{len(rows)} referenced paths, {sum(1 for r in rows if 'MISSING' in r[2] or 'NO MATCH' in r[2])} unresolved, {len(extra)} extra figures, {len(paper)} paper files")
    for r in rows:
        if "MISSING" in r[2] or "NO MATCH" in r[2]:
            print("  unresolved:", r[0], r[3])


if __name__ == "__main__":
    main()
